packages:
  - 'apps/*'
  - 'packages/*'
  - 'tools'
  - 'tools/app'
  - 'tools/dashboard'
  - 'tools/eslint'
  - 'tools/discord'
overrides:
  google-auth-library: 10.7.0
  fast-uri: ^3
  '@types/react': ^19.0.0
  '@types/react-dom': ^19.0.0
allowBuilds:
  esbuild: set this to true or false
  msgpackr-extract: set this to true or false
  sharp: set this to true or false
