'use client'

import { forwardRef, useMemo, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { api, ApiError } from '../api/client'
import { useI18n } from '../hooks/useI18n'
import { useActiveClinic } from '../hooks/useActiveClinic'
import { useAuthStore } from '../store/auth'
import type { AppointmentWithNames, Conversation, Doctor, Service, SlotsResponse } from '../types'
import { bookingPresentationSource, canUseParallelBooking, manualSlotControl } from '../bookingPresentation'
import { activeAppointmentsByClinicDate, appointmentsForClinicDate } from '../clinicCalendar'
import { buildManualParallelBookingFields, isManualParallelBookingComplete } from '../manualParallelBooking'

function localDate(d: Date): string { const off = d.getTimezoneOffset() * 60_000; return new Date(d.getTime() - off).toISOString().slice(0, 10) }
function monthStart(date: string): Date { const d = new Date(`${date}T12:00:00`); return new Date(d.getFullYear(), d.getMonth(), 1) }
function monthDays(date: string): string[] { const first = monthStart(date); const start = new Date(first); start.setDate(1 - first.getDay()); return Array.from({ length: 42 }, (_, i) => { const d = new Date(start); d.setDate(start.getDate() + i); return localDate(d) }) }

export const AppointmentBookingCard = forwardRef<HTMLElement, { conversationId: string; expanded?: boolean; onToggle?: () => void }>(function AppointmentBookingCard({ conversationId }, ref) {
  const { t, language } = useI18n(); const qc = useQueryClient(); const { clinicId } = useActiveClinic(); const role = useAuthStore((s) => s.user?.role)
  const canManuallyBook = canUseParallelBooking(role); const today = localDate(new Date())
  const [doctorId, setDoctorId] = useState(''); const [date, setDate] = useState(today); const [slot, setSlot] = useState(''); const [parallel, setParallel] = useState(false); const [parallelPatientName, setParallelPatientName] = useState(''); const [parallelServiceId, setParallelServiceId] = useState(''); const [parallelReason, setParallelReason] = useState(''); const [errorKey, setErrorKey] = useState<string | null>(null); const [booked, setBooked] = useState(false)
  const clearParallelDetails = () => { setParallel(false); setParallelPatientName(''); setParallelServiceId(''); setParallelReason('') }
  const conversationQuery = useQuery({ queryKey: ['conversation', conversationId], queryFn: () => api.get<{ conversation: Conversation }>(`/conversations/${conversationId}`) }); const patientId = conversationQuery.data?.conversation?.patientId ?? null
  const clinicQuery = useQuery({ queryKey: ['clinic', clinicId], enabled: Boolean(clinicId), queryFn: () => api.get<{ clinic: { timezone?: string | null } }>(`/clinics/${clinicId}`) }); const timezone = clinicQuery.data?.clinic.timezone || 'America/Guatemala'
  const doctorsQuery = useQuery({ queryKey: ['doctors', clinicId], enabled: Boolean(clinicId), queryFn: () => api.get<{ doctors: Doctor[] }>(`/clinics/${clinicId}/doctors`) }); const doctors = (doctorsQuery.data?.doctors ?? []).filter((d) => d.isActive)
  const servicesQuery = useQuery({ queryKey: ['services', clinicId], enabled: Boolean(clinicId), queryFn: () => api.get<{ services: Service[] }>(`/clinics/${clinicId}/services`) }); const services = (servicesQuery.data?.services ?? []).filter((service) => service.isActive)
  const days = useMemo(() => monthDays(date), [date]); const month = monthStart(date); const monthKey = `${month.getFullYear()}-${String(month.getMonth() + 1).padStart(2, '0')}`
  const nextMonth = new Date(month); nextMonth.setMonth(nextMonth.getMonth() + 1); const nextMonthKey = `${nextMonth.getFullYear()}-${String(nextMonth.getMonth() + 1).padStart(2, '0')}-01`
  const appointmentsQuery = useQuery({ queryKey: ['appointments', clinicId, monthKey, doctorId], enabled: Boolean(clinicId), queryFn: () => api.get<{ appointments: AppointmentWithNames[] }>(`/clinics/${clinicId}/appointments?${new URLSearchParams({ from: `${monthKey}-01`, to: nextMonthKey, ...(doctorId ? { doctorId } : {}) })}`) })
  const slotsQuery = useQuery({ queryKey: ['slots', clinicId, doctorId, date, canManuallyBook, parallelServiceId], enabled: Boolean(clinicId && doctorId && date), queryFn: () => api.get<SlotsResponse>(`/clinics/${clinicId}/appointments/slots?${new URLSearchParams({ doctorId, date, ...(parallelServiceId ? { serviceId: parallelServiceId } : {}), ...(canManuallyBook ? { includeBooked: 'true' } : {}) })}`) })
  const bookingsByDate = useMemo(() => activeAppointmentsByClinicDate(appointmentsQuery.data?.appointments ?? [], timezone), [appointmentsQuery.data?.appointments, timezone])
  const selectedAppointments = useMemo(() => appointmentsForClinicDate(appointmentsQuery.data?.appointments ?? [], date, timezone), [appointmentsQuery.data?.appointments, date, timezone])
  const parallelDetails = { patientName: parallelPatientName, serviceId: parallelServiceId, reason: parallelReason }
  const bookMutation = useMutation({ mutationFn: () => api.post(`/clinics/${clinicId}/appointments`, { doctorId, date, start: slot, ...(parallel ? buildManualParallelBookingFields(parallelDetails) : { patientId }) }), onMutate: () => { setErrorKey(null); setBooked(false) }, onSuccess: () => { setBooked(true); setSlot(''); clearParallelDetails(); qc.invalidateQueries({ queryKey: ['patient-appointments', patientId] }); qc.invalidateQueries({ queryKey: ['appointments', clinicId] }); qc.invalidateQueries({ queryKey: ['slots', clinicId, doctorId, date] }) }, onError: (e) => setErrorKey(e instanceof ApiError && e.status === 409 ? 'cal.slotTaken' : e instanceof ApiError && e.status === 422 ? 'cal.overbookingReason' : 'cal.bookError') })
  const changeMonth = (delta: number) => { const next = new Date(month); next.setMonth(next.getMonth() + delta); setDate(localDate(next)); setSlot(''); clearParallelDetails() }; const monthLabel = new Intl.DateTimeFormat(language === 'es' ? 'es' : 'en', { month: 'long', year: 'numeric' }).format(month); const weekdays = language === 'es' ? ['Do', 'Lu', 'Ma', 'Mi', 'Ju', 'Vi', 'Sá'] : ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa']
  return <section ref={ref} tabIndex={-1} className="rounded-[var(--crm-border-radius-md)] border border-[var(--crm-border-color)] bg-[var(--crm-card-bg)] shadow-[var(--crm-shadow-sm)] outline-none focus:ring-4 focus:ring-[var(--crm-hover-bg)]"><div className="flex items-center justify-between gap-2 px-4 py-3"><span className="text-xs font-bold uppercase tracking-wide text-[var(--crm-text-muted)]">📅 {t('cal.title')}</span><span className="text-[10px] text-[var(--crm-text-muted)]">{t('cal.secretaryOnly')}</span></div><div className="space-y-3 border-t border-[var(--crm-border-color)] px-4 py-3">
    <label className="block"><span className="mb-1 block text-[11px] font-semibold text-[var(--crm-text-muted)]">{t('cal.doctor')}</span><select value={doctorId} onChange={(e) => { setDoctorId(e.target.value); setSlot(''); clearParallelDetails(); setBooked(false) }} className="w-full rounded-lg border border-[var(--crm-border-color)] bg-[var(--crm-input-bg)] px-2 py-1.5 text-xs"><option value="">{t('cal.selectDoctor')}</option>{doctors.map((d) => <option key={d.id} value={d.id}>{d.name}{d.specialty ? ` · ${d.specialty}` : ''}</option>)}</select></label>
    <div className="flex items-center justify-between"><button type="button" onClick={() => changeMonth(-1)} aria-label={t('cal.previousMonth')} className="px-2 text-sm">‹</button><span className="text-sm font-bold capitalize">{monthLabel}</span><button type="button" onClick={() => changeMonth(1)} aria-label={t('cal.nextMonth')} className="px-2 text-sm">›</button></div>
    <div className="grid grid-cols-7 gap-1 text-center text-[10px] text-[var(--crm-text-muted)]">{weekdays.map((day) => <span key={day}>{day}</span>)}{days.map((day) => { const inMonth = day.slice(0, 7) === monthKey; const selected = day === date; const entries = bookingsByDate.get(day) ?? []; return <button key={day} type="button" onClick={() => { setDate(day); setSlot(''); clearParallelDetails(); setBooked(false) }} className={`relative min-h-8 rounded-md text-xs ${!inMonth ? 'opacity-30' : ''} ${selected ? 'bg-[var(--crm-primary-color)] text-white' : 'hover:bg-[var(--crm-hover-bg)]'}`}><span>{Number(day.slice(8))}</span>{entries.length > 0 && <span className="absolute bottom-0.5 left-1/2 flex -translate-x-1/2 gap-0.5">{entries.slice(0, 3).map((a) => { const source = bookingPresentationSource(a); const title = source === 'automated' ? t('cal.bookedByAi') : source === 'secretary' ? t('cal.bookedBySecretary') : t('cal.booked'); const color = source === 'automated' ? 'bg-violet-500' : source === 'secretary' ? 'bg-slate-500' : 'bg-amber-500'; return <span key={a.id} title={title} className={`h-1.5 w-1.5 rounded-full ${color}`} /> })}</span>}</button> })}</div>
    <div>
      <p className="mb-1.5 text-[11px] font-semibold text-[var(--crm-text-muted)]">{t('cal.bookedSchedules')} · {date}</p>
      {appointmentsQuery.isLoading ? <p className="text-[10px] text-[var(--crm-text-muted)]">{t('cal.loading')}</p> : selectedAppointments.length === 0 ? <p className="text-[10px] text-[var(--crm-text-muted)]">{t('cal.noBookedSchedules')}</p> : <div className="max-h-24 space-y-1 overflow-y-auto pr-1">{selectedAppointments.map((appointment) => { const source = bookingPresentationSource(appointment); const color = source === 'automated' ? 'bg-violet-500' : source === 'secretary' ? 'bg-slate-500' : 'bg-amber-500'; const sourceLabel = source === 'automated' ? t('cal.bookedByAi') : source === 'secretary' ? t('cal.bookedBySecretary') : t('cal.booked'); const time = new Intl.DateTimeFormat(language === 'es' ? 'es' : 'en', { hour: '2-digit', minute: '2-digit', timeZone: timezone }).format(new Date(appointment.startTime)); return <div key={appointment.id} className="rounded-md border border-[var(--crm-border-color)] bg-[var(--crm-input-bg)] px-2 py-1.5 text-[10px]"><div className="flex items-center gap-1.5"><span title={sourceLabel} className={`h-1.5 w-1.5 shrink-0 rounded-full ${color}`} /><span className="shrink-0 font-bold text-[var(--crm-text-main)]">{time}</span><span className="min-w-0 flex-1 truncate font-semibold text-[var(--crm-text-main)]">{appointment.patientName || t('cal.unknownPatient')}</span><span className="shrink-0 text-[var(--crm-text-muted)]">{t(`cal.status.${appointment.status}` as const)}</span></div>{appointment.doctorName && <p className="mt-0.5 truncate pl-3 text-[9px] text-[var(--crm-text-muted)]">{appointment.doctorName}{appointment.serviceName ? ` · ${appointment.serviceName}` : ''}</p>}</div> })}</div>}
    </div>
    {doctorId && (slotsQuery.isLoading ? <p className="text-[11px] text-[var(--crm-text-muted)]">{t('cal.slotsLoading')}</p> : slotsQuery.data && !slotsQuery.data.working ? <p className="text-[11px] text-[var(--crm-text-muted)]">{t('cal.dayOff')}</p> : slotsQuery.data?.slots.length === 0 ? <p className="text-[11px] text-[var(--crm-text-muted)]">{t('cal.noSlots')}</p> : <div><p className="mb-1.5 text-[11px] font-semibold text-[var(--crm-text-muted)]">{t('cal.pickSlot')} · {date}</p><div className="grid h-40 grid-cols-2 gap-1.5 overflow-y-auto rounded-lg border border-[var(--crm-border-color)] bg-[var(--crm-input-bg)] p-1.5 pr-1">{slotsQuery.data?.slots.map((s) => { const occupied = (s.bookedCount ?? 0) > 0; const control = manualSlotControl(role, s); const aiCount = s.bookedByAiCount ?? 0; const secretaryCount = s.bookedBySecretaryCount ?? 0; return <div key={s.start} className="flex items-center gap-1"><button type="button" disabled={occupied} onClick={() => { setSlot(s.start); clearParallelDetails(); setBooked(false) }} title={occupied ? t('cal.slotBooked') : undefined} className={`min-w-0 flex-1 rounded-md border px-1 py-1 text-xs font-semibold ${occupied ? 'cursor-not-allowed border-[var(--crm-border-color)] bg-[var(--crm-hover-bg)] text-[var(--crm-text-muted)]' : slot === s.start && !parallel ? 'border-[var(--crm-primary-color)] bg-[var(--crm-primary-color)] text-white' : 'border-[var(--crm-border-color)] hover:bg-[var(--crm-hover-bg)]'}`}><span>{s.start}</span>{occupied && <span className="ml-1 inline-flex gap-1 text-[9px] font-medium"><span className="text-violet-500">AI {aiCount}</span><span className="text-slate-500">S {secretaryCount}</span></span>}</button>{control.visible && <button type="button" disabled={!control.enabled} title={control.enabled ? (control.overbook ? t('cal.parallel') : t('cal.book')) : t('cal.capacityReached')} aria-label={`${control.overbook ? t('cal.parallel') : t('cal.book')} ${s.start}`} onClick={() => { setSlot(s.start); clearParallelDetails(); setParallel(control.overbook); setBooked(false) }} className="rounded-md border border-dashed border-[var(--crm-primary-color)] px-2 py-1 text-sm font-bold text-[var(--crm-primary-color)] disabled:cursor-not-allowed disabled:border-[var(--crm-border-color)] disabled:text-[var(--crm-text-muted)]">+</button>}</div> })}</div></div>)}
    {parallel && <fieldset className="space-y-2 rounded-lg border border-[var(--crm-border-color)] p-2.5"><legend className="px-1 text-[11px] font-semibold text-[var(--crm-text-muted)]">{t('cal.parallelDetails')}</legend><label className="block"><span className="mb-1 block text-[11px] font-semibold text-[var(--crm-text-muted)]">{t('cal.parallelPatientName')}</span><input value={parallelPatientName} onChange={(e) => setParallelPatientName(e.target.value)} placeholder={t('cal.parallelPatientNamePlaceholder')} autoComplete="name" className="w-full rounded-lg border border-[var(--crm-border-color)] bg-[var(--crm-input-bg)] px-2 py-1.5 text-xs" /></label><label className="block"><span className="mb-1 block text-[11px] font-semibold text-[var(--crm-text-muted)]">{t('cal.parallelService')}</span><select value={parallelServiceId} onChange={(e) => setParallelServiceId(e.target.value)} className="w-full rounded-lg border border-[var(--crm-border-color)] bg-[var(--crm-input-bg)] px-2 py-1.5 text-xs"><option value="">{servicesQuery.isLoading ? t('cal.loading') : t('cal.selectService')}</option>{services.map((service) => <option key={service.id} value={service.id}>{service.name}</option>)}</select></label><label className="block"><span className="mb-1 block text-[11px] font-semibold text-[var(--crm-text-muted)]">{t('cal.parallelAppointmentReason')}</span><textarea value={parallelReason} onChange={(e) => setParallelReason(e.target.value)} rows={2} placeholder={t('cal.parallelAppointmentReasonPlaceholder')} className="w-full resize-none rounded-lg border border-[var(--crm-border-color)] bg-[var(--crm-input-bg)] px-2 py-1.5 text-xs" /></label></fieldset>}<div className="flex flex-wrap gap-3 text-[10px] text-[var(--crm-text-muted)]"><span><i className="mr-1 inline-block h-1.5 w-1.5 rounded-full bg-violet-500" />{t('cal.bookedByAi')}</span><span><i className="mr-1 inline-block h-1.5 w-1.5 rounded-full bg-slate-500" />{t('cal.bookedBySecretary')}</span><span><i className="mr-1 inline-block h-1.5 w-1.5 rounded-full bg-amber-500" />{t('cal.booked')}</span></div>{errorKey && <p className="text-[11px] font-medium text-red-600">⚠ {t(errorKey)}</p>}{booked && <p className="text-[11px] font-medium text-emerald-600">✓ {t('cal.booked')}</p>}<button type="button" onClick={() => bookMutation.mutate()} disabled={(!parallel && !patientId) || !doctorId || !slot || (parallel && !isManualParallelBookingComplete(parallelDetails)) || bookMutation.isPending} className="w-full rounded-lg bg-[var(--crm-primary-color)] px-3 py-2 text-xs font-bold text-white disabled:opacity-60">{bookMutation.isPending ? t('cal.booking') : parallel ? t('cal.confirmParallel') : t('cal.confirm')}</button>
  </div></section>
})
