'use client'

import { forwardRef, useMemo, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { api, ApiError } from '../api/client'
import { useI18n } from '../hooks/useI18n'
import { useActiveClinic } from '../hooks/useActiveClinic'
import { useAuthStore } from '../store/auth'
import type { AppointmentWithNames, Conversation, Doctor, SlotsResponse } from '../types'

function localDate(d: Date): string { const off = d.getTimezoneOffset() * 60_000; return new Date(d.getTime() - off).toISOString().slice(0, 10) }
function monthStart(date: string): Date { const d = new Date(`${date}T12:00:00`); return new Date(d.getFullYear(), d.getMonth(), 1) }
function monthDays(date: string): string[] { const first = monthStart(date); const start = new Date(first); start.setDate(1 - first.getDay()); return Array.from({ length: 42 }, (_, i) => { const d = new Date(start); d.setDate(start.getDate() + i); return localDate(d) }) }

export const AppointmentBookingCard = forwardRef<HTMLElement, { conversationId: string; expanded?: boolean; onToggle?: () => void }>(function AppointmentBookingCard({ conversationId }, ref) {
  const { t, language } = useI18n(); const qc = useQueryClient(); const { clinicId } = useActiveClinic(); const role = useAuthStore((s) => s.user?.role)
  const canParallelBook = role === 'secretary' || role === 'clinic_admin' || role === 'ia_studio_admin'; const today = localDate(new Date())
  const [doctorId, setDoctorId] = useState(''); const [date, setDate] = useState(today); const [slot, setSlot] = useState(''); const [parallel, setParallel] = useState(false); const [reason, setReason] = useState(''); const [errorKey, setErrorKey] = useState<string | null>(null); const [booked, setBooked] = useState(false)
  const conversationQuery = useQuery({ queryKey: ['conversation', conversationId], queryFn: () => api.get<{ conversation: Conversation }>(`/conversations/${conversationId}`) }); const patientId = conversationQuery.data?.conversation?.patientId ?? null
  const doctorsQuery = useQuery({ queryKey: ['doctors', clinicId], enabled: Boolean(clinicId), queryFn: () => api.get<{ doctors: Doctor[] }>(`/clinics/${clinicId}/doctors`) }); const doctors = (doctorsQuery.data?.doctors ?? []).filter((d) => d.isActive)
  const days = useMemo(() => monthDays(date), [date]); const month = monthStart(date); const monthKey = `${month.getFullYear()}-${String(month.getMonth() + 1).padStart(2, '0')}`
  const nextMonth = new Date(month); nextMonth.setMonth(nextMonth.getMonth() + 1); const nextMonthKey = `${nextMonth.getFullYear()}-${String(nextMonth.getMonth() + 1).padStart(2, '0')}-01`
  const appointmentsQuery = useQuery({ queryKey: ['appointments', clinicId, monthKey, doctorId], enabled: Boolean(clinicId), queryFn: () => api.get<{ appointments: AppointmentWithNames[] }>(`/clinics/${clinicId}/appointments?${new URLSearchParams({ from: `${monthKey}-01`, to: nextMonthKey, ...(doctorId ? { doctorId } : {}) })}`) })
  const slotsQuery = useQuery({ queryKey: ['slots', clinicId, doctorId, date, canParallelBook], enabled: Boolean(clinicId && doctorId && date), queryFn: () => api.get<SlotsResponse>(`/clinics/${clinicId}/appointments/slots?${new URLSearchParams({ doctorId, date, ...(canParallelBook ? { includeBooked: 'true' } : {}) })}`) })
  const bookingsByDate = useMemo(() => { const map = new Map<string, AppointmentWithNames[]>(); for (const appointment of appointmentsQuery.data?.appointments ?? []) { const key = appointment.startTime.slice(0, 10); map.set(key, [...(map.get(key) ?? []), appointment]) } return map }, [appointmentsQuery.data?.appointments])
  const bookMutation = useMutation({ mutationFn: () => api.post(`/clinics/${clinicId}/appointments`, { patientId, doctorId, date, start: slot, ...(parallel ? { overbook: true, overbookingReason: reason.trim() } : {}) }), onMutate: () => { setErrorKey(null); setBooked(false) }, onSuccess: () => { setBooked(true); setSlot(''); setParallel(false); setReason(''); qc.invalidateQueries({ queryKey: ['patient-appointments', patientId] }); qc.invalidateQueries({ queryKey: ['appointments', clinicId] }); qc.invalidateQueries({ queryKey: ['slots', clinicId, doctorId, date] }) }, onError: (e) => setErrorKey(e instanceof ApiError && e.status === 409 ? 'cal.slotTaken' : e instanceof ApiError && e.status === 422 ? 'cal.overbookingReason' : 'cal.bookError') })
  const changeMonth = (delta: number) => { const next = new Date(month); next.setMonth(next.getMonth() + delta); setDate(localDate(next)); setSlot('') }; const monthLabel = new Intl.DateTimeFormat(language === 'es' ? 'es' : 'en', { month: 'long', year: 'numeric' }).format(month); const weekdays = language === 'es' ? ['Do', 'Lu', 'Ma', 'Mi', 'Ju', 'Vi', 'Sá'] : ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa']
  return <section ref={ref} className="rounded-[var(--crm-border-radius-md)] border border-[var(--crm-border-color)] bg-[var(--crm-card-bg)] shadow-[var(--crm-shadow-sm)]"><div className="flex items-center justify-between gap-2 px-4 py-3"><span className="text-xs font-bold uppercase tracking-wide text-[var(--crm-text-muted)]">📅 {t('cal.title')}</span><span className="text-[10px] text-[var(--crm-text-muted)]">{t('cal.secretaryOnly')}</span></div><div className="space-y-3 border-t border-[var(--crm-border-color)] px-4 py-3">
    <label className="block"><span className="mb-1 block text-[11px] font-semibold text-[var(--crm-text-muted)]">{t('cal.doctor')}</span><select value={doctorId} onChange={(e) => { setDoctorId(e.target.value); setSlot(''); setBooked(false) }} className="w-full rounded-lg border border-[var(--crm-border-color)] bg-[var(--crm-input-bg)] px-2 py-1.5 text-xs"><option value="">{t('cal.selectDoctor')}</option>{doctors.map((d) => <option key={d.id} value={d.id}>{d.name}{d.specialty ? ` · ${d.specialty}` : ''}</option>)}</select></label>
    <div className="flex items-center justify-between"><button type="button" onClick={() => changeMonth(-1)} aria-label={t('cal.previousMonth')} className="px-2 text-sm">‹</button><span className="text-sm font-bold capitalize">{monthLabel}</span><button type="button" onClick={() => changeMonth(1)} aria-label={t('cal.nextMonth')} className="px-2 text-sm">›</button></div>
    <div className="grid grid-cols-7 gap-1 text-center text-[10px] text-[var(--crm-text-muted)]">{weekdays.map((day) => <span key={day}>{day}</span>)}{days.map((day) => { const inMonth = day.slice(0, 7) === monthKey; const selected = day === date; const entries = bookingsByDate.get(day) ?? []; return <button key={day} type="button" onClick={() => { setDate(day); setSlot(''); setBooked(false) }} className={`relative min-h-8 rounded-md text-xs ${!inMonth ? 'opacity-30' : ''} ${selected ? 'bg-[var(--crm-primary-color)] text-white' : 'hover:bg-[var(--crm-hover-bg)]'}`}><span>{Number(day.slice(8))}</span>{entries.length > 0 && <span className="absolute bottom-0.5 left-1/2 flex -translate-x-1/2 gap-0.5">{entries.slice(0, 3).map((a) => <span key={a.id} title={a.conversationId ? t('cal.bookedByAi') : t('cal.bookedBySecretary')} className={`h-1.5 w-1.5 rounded-full ${a.conversationId ? 'bg-violet-500' : 'bg-slate-500'}`} />)}</span>}</button> })}</div>
    {doctorId && (slotsQuery.isLoading ? <p className="text-[11px] text-[var(--crm-text-muted)]">{t('cal.slotsLoading')}</p> : slotsQuery.data && !slotsQuery.data.working ? <p className="text-[11px] text-[var(--crm-text-muted)]">{t('cal.dayOff')}</p> : slotsQuery.data?.slots.length === 0 ? <p className="text-[11px] text-[var(--crm-text-muted)]">{t('cal.noSlots')}</p> : <div><p className="mb-1.5 text-[11px] font-semibold text-[var(--crm-text-muted)]">{t('cal.pickSlot')} · {date}</p><div className="grid grid-cols-2 gap-1.5">{slotsQuery.data?.slots.map((s) => { const occupied = (s.bookedCount ?? 0) > 0; const parallelAvailable = s.parallelAvailable ?? occupied; return <div key={s.start} className="flex items-center gap-1"><button type="button" disabled={occupied} onClick={() => { setSlot(s.start); setParallel(false); setBooked(false) }} title={occupied ? t('cal.slotBooked') : undefined} className={`min-w-0 flex-1 rounded-md border px-1 py-1 text-xs font-semibold ${occupied ? 'cursor-not-allowed border-[var(--crm-border-color)] bg-[var(--crm-hover-bg)] text-[var(--crm-text-muted)]' : slot === s.start && !parallel ? 'border-[var(--crm-primary-color)] bg-[var(--crm-primary-color)] text-white' : 'border-[var(--crm-border-color)] hover:bg-[var(--crm-hover-bg)]'}`}>{s.start}{occupied ? ` · ${t('cal.booked')}` : ''}</button>{canParallelBook && parallelAvailable && <button type="button" title={t('cal.parallel')} aria-label={`${t('cal.parallel')} ${s.start}`} onClick={() => { setSlot(s.start); setParallel(true); setBooked(false) }} className="rounded-md border border-dashed border-[var(--crm-primary-color)] px-2 py-1 text-sm font-bold text-[var(--crm-primary-color)]">+</button>}</div> })}</div></div>)}
    {parallel && <label className="block"><span className="mb-1 block text-[11px] font-semibold text-[var(--crm-text-muted)]">{t('cal.parallelReason')}</span><input value={reason} onChange={(e) => setReason(e.target.value)} placeholder={t('cal.parallelReasonPlaceholder')} className="w-full rounded-lg border border-[var(--crm-border-color)] bg-[var(--crm-input-bg)] px-2 py-1.5 text-xs" /></label>}<div className="flex flex-wrap gap-3 text-[10px] text-[var(--crm-text-muted)]"><span><i className="mr-1 inline-block h-1.5 w-1.5 rounded-full bg-violet-500" />{t('cal.bookedByAi')}</span><span><i className="mr-1 inline-block h-1.5 w-1.5 rounded-full bg-slate-500" />{t('cal.bookedBySecretary')}</span></div>{errorKey && <p className="text-[11px] font-medium text-red-600">⚠ {t(errorKey)}</p>}{booked && <p className="text-[11px] font-medium text-emerald-600">✓ {t('cal.booked')}</p>}<button type="button" onClick={() => bookMutation.mutate()} disabled={!patientId || !doctorId || !slot || (parallel && !reason.trim()) || bookMutation.isPending} className="w-full rounded-lg bg-[var(--crm-primary-color)] px-3 py-2 text-xs font-bold text-white disabled:opacity-60">{bookMutation.isPending ? t('cal.booking') : parallel ? t('cal.confirmParallel') : t('cal.confirm')}</button>
  </div></section>
})
