import type { Sql } from '../client.js'
import { toJson } from '../client.js'
export type WorkflowApprovalStatus = 'pending' | 'approved' | 'rejected' | 'expired' | 'resuming' | 'resumed' | 'failed' | 'cancelled'
export interface WorkflowApproval { id: string; clinicId: string; workflowId: string; nodeId: string; runKey: string; conversationId: string | null; patientId: string | null; resumeNodeId: string | null; context: Record<string, unknown>; status: WorkflowApprovalStatus; expiresAt: string; decidedBy: string | null; decidedAt: string | null; failureReason: string | null; createdAt: string; updatedAt: string }
export interface WorkflowAiDraft { id: string; clinicId: string; workflowId: string; nodeId: string; runKey: string; conversationId: string | null; patientId: string | null; prompt: string; content: string; sources: Array<{ title: string; similarity?: number }>; status: 'pending_review' | 'accepted' | 'rejected' | 'failed' | 'cancelled'; errorReason: string | null; createdAt: string; updatedAt: string }
export interface CreateWorkflowApprovalInput { clinicId: string; workflowId: string; nodeId: string; runKey: string; conversationId?: string; patientId?: string; resumeNodeId?: string; context: Record<string, unknown>; expiresAt: string }
export interface CreateWorkflowDraftInput { clinicId: string; workflowId: string; nodeId: string; runKey: string; conversationId?: string; patientId?: string; prompt: string; content: string; sources?: Array<{ title: string; similarity?: number }> }
export interface WorkflowApprovalsRepository { createPending(input: CreateWorkflowApprovalInput): Promise<WorkflowApproval>; findById(clinicId: string, id: string): Promise<WorkflowApproval | null>; listPending(clinicId: string): Promise<WorkflowApproval[]>; decide(clinicId: string, id: string, decision: 'approved' | 'rejected', actorId: string): Promise<WorkflowApproval | null>; claimResume(clinicId: string, id: string): Promise<WorkflowApproval | null>; markResumed(clinicId: string, id: string): Promise<void>; markFailed(clinicId: string, id: string, reason: string): Promise<void>; createDraft(input: CreateWorkflowDraftInput): Promise<WorkflowAiDraft>; listDrafts(clinicId: string): Promise<WorkflowAiDraft[]> }
export function createWorkflowApprovalsRepository(sql: Sql): WorkflowApprovalsRepository { return {
  async createPending(input) { const rows = await sql<WorkflowApproval[]>`INSERT INTO workflow_approvals (clinic_id, workflow_id, node_id, run_key, conversation_id, patient_id, resume_node_id, context, expires_at) VALUES (${input.clinicId}, ${input.workflowId}, ${input.nodeId}, ${input.runKey}, ${input.conversationId ?? null}, ${input.patientId ?? null}, ${input.resumeNodeId ?? null}, ${sql.json(toJson(input.context))}, ${input.expiresAt}) ON CONFLICT (clinic_id, workflow_id, node_id, run_key) DO UPDATE SET updated_at = workflow_approvals.updated_at RETURNING *`; return rows[0]! },
  async findById(clinicId, id) { const rows = await sql<WorkflowApproval[]>`SELECT * FROM workflow_approvals WHERE clinic_id = ${clinicId} AND id = ${id} LIMIT 1`; return rows[0] ?? null },
  async listPending(clinicId) { await sql`UPDATE workflow_approvals SET status = 'expired' WHERE clinic_id = ${clinicId} AND status = 'pending' AND expires_at <= NOW()`; return sql<WorkflowApproval[]>`SELECT * FROM workflow_approvals WHERE clinic_id = ${clinicId} AND status = 'pending' ORDER BY created_at DESC` },
  async decide(clinicId, id, decision, actorId) { const rows = await sql<WorkflowApproval[]>`UPDATE workflow_approvals SET status = ${decision}, decided_by = ${actorId}, decided_at = NOW() WHERE clinic_id = ${clinicId} AND id = ${id} AND status = 'pending' AND expires_at > NOW() RETURNING *`; return rows[0] ?? null },
  async claimResume(clinicId, id) { const rows = await sql<WorkflowApproval[]>`UPDATE workflow_approvals SET status = 'resuming' WHERE clinic_id = ${clinicId} AND id = ${id} AND status = 'approved' RETURNING *`; return rows[0] ?? null },
  async markResumed(clinicId, id) { await sql`UPDATE workflow_approvals SET status = 'resumed' WHERE clinic_id = ${clinicId} AND id = ${id} AND status = 'resuming'` }, async markFailed(clinicId, id, reason) { await sql`UPDATE workflow_approvals SET status = 'failed', failure_reason = ${reason.slice(0, 1000)} WHERE clinic_id = ${clinicId} AND id = ${id} AND status = 'resuming'` },
  async createDraft(input) { const rows = await sql<WorkflowAiDraft[]>`INSERT INTO workflow_ai_drafts (clinic_id, workflow_id, node_id, run_key, conversation_id, patient_id, prompt, content, sources) VALUES (${input.clinicId}, ${input.workflowId}, ${input.nodeId}, ${input.runKey}, ${input.conversationId ?? null}, ${input.patientId ?? null}, ${input.prompt}, ${input.content}, ${sql.json(toJson(input.sources ?? []))}) ON CONFLICT (clinic_id, workflow_id, node_id, run_key) DO UPDATE SET updated_at = workflow_ai_drafts.updated_at RETURNING *`; return rows[0]! }, async listDrafts(clinicId) { return sql<WorkflowAiDraft[]>`SELECT * FROM workflow_ai_drafts WHERE clinic_id = ${clinicId} ORDER BY created_at DESC LIMIT 100` },
} }
