import { writeFile } from 'node:fs/promises'
import path from 'node:path'

/**
 * Every value the setup wizard collects. These map 1:1 to the `.env` keys the
 * four Docmee services read at boot. `redisUrl` defaults to a local Redis when
 * the operator leaves it blank.
 */
export interface InstallerConfig {
  supabaseUrl: string
  supabaseAnonKey: string
  supabaseServiceKey: string
  anthropicApiKey: string
  deepseekApiKey: string
  deepgramApiKey: string
  resendApiKey: string
  metaAppSecret: string
  metaVerifyToken: string
  redisUrl: string
  jwtSecret: string
  jwtRefreshSecret: string
  licenseKey: string
}

export function emptyConfig(): InstallerConfig {
  return {
    supabaseUrl: '',
    supabaseAnonKey: '',
    supabaseServiceKey: '',
    anthropicApiKey: '',
    deepseekApiKey: '',
    deepgramApiKey: '',
    resendApiKey: '',
    metaAppSecret: '',
    metaVerifyToken: '',
    redisUrl: '',
    jwtSecret: '',
    jwtRefreshSecret: '',
    licenseKey: '',
  }
}

const ENV_KEYS: Array<[keyof InstallerConfig, string]> = [
  ['supabaseUrl', 'SUPABASE_URL'],
  ['supabaseAnonKey', 'SUPABASE_ANON_KEY'],
  ['supabaseServiceKey', 'SUPABASE_SERVICE_KEY'],
  ['anthropicApiKey', 'ANTHROPIC_API_KEY'],
  ['deepseekApiKey', 'DEEPSEEK_API_KEY'],
  ['deepgramApiKey', 'DEEPGRAM_API_KEY'],
  ['resendApiKey', 'RESEND_API_KEY'],
  ['metaAppSecret', 'META_APP_SECRET'],
  ['metaVerifyToken', 'META_VERIFY_TOKEN'],
  ['redisUrl', 'REDIS_URL'],
  ['jwtSecret', 'JWT_SECRET'],
  ['jwtRefreshSecret', 'JWT_REFRESH_SECRET'],
  ['licenseKey', 'LICENSE_KEY'],
]

function escapeValue(value: string): string {
  // Quote values that contain whitespace or characters dotenv parses specially.
  if (value === '' || /^[A-Za-z0-9_./:@-]+$/.test(value)) return value
  return `"${value.replace(/(["\\])/g, '\\$1')}"`
}

/** Render the collected config as a deterministic, ordered `.env` file. */
export function buildEnvContent(config: InstallerConfig): string {
  const redisUrl = config.redisUrl.trim() || 'redis://127.0.0.1:6379'
  const lines = ['# Generated by Docmee DeployKit', `NODE_ENV=production`]
  for (const [key, envName] of ENV_KEYS) {
    const value = key === 'redisUrl' ? redisUrl : config[key]
    lines.push(`${envName}=${escapeValue(value)}`)
  }
  return `${lines.join('\n')}\n`
}

/** Write `.env` into the installed app directory. Returns the file path. */
export async function writeEnvFile(installDir: string, config: InstallerConfig): Promise<string> {
  const envPath = path.join(installDir, '.env')
  await writeFile(envPath, buildEnvContent(config), 'utf8')
  return envPath
}

/** Keys the operator must supply before we can start the services. */
export function missingRequiredKeys(config: InstallerConfig): string[] {
  const required: Array<keyof InstallerConfig> = [
    'supabaseUrl',
    'supabaseServiceKey',
    'anthropicApiKey',
    'metaAppSecret',
    'metaVerifyToken',
    'jwtSecret',
    'jwtRefreshSecret',
    'licenseKey',
  ]
  return required.filter((key) => config[key].trim() === '')
}
