export const teachingCopy = {
  en: {
    mode: 'Train J.zel', chat: 'Docmee Help', clinic: 'Teaching clinic', doctor: 'Doctor', allDoctors: 'Whole clinic',
    recent: 'Recent lessons in this scope', resume: 'Open lesson',
    language: 'Knowledge language', allLanguages: 'Any language', intro: 'Write a clinic fact or correction. A draft stays private until you review and approve it.',
    title: 'Entry title', content: 'What should the agent know?', target: 'Add or update', newEntry: 'Add a new entry',
    create: 'Prepare proposal', busy: 'Working…', draft: 'Draft · awaiting your confirmation', approve: 'Approve this exact entry',
    confirm: 'I checked the clinic, scope and related entries. This information is correct and approved for patient answers.',
    related: 'Possible duplicates or conflicts', warning: 'Related entries are a bounded search, not proof that all conflicts have been found. Update an existing entry when replacing a fact.',
    none: 'No related entries found.', previous: 'Current entry', proposed: 'Proposed entry', edit: 'Revise proposal', status: 'Publication status',
    approved: 'Approved · indexing in progress. Keyword retrieval may already use this entry.',
    ready: 'Ready for the agent to retrieve. Answer safety checks still apply.',
    indexing_failed: 'Approved · indexing failed. Retry indexing to complete preparation.',
    superseded: 'This version is no longer available. Review the current entry in Knowledge Base.',
    rejected: 'Rejected', pending_review: 'Draft', retry: 'Retry indexing', refresh: 'Refresh status',
    history: 'Change history', restore: 'Restore this content', restoreConfirm: 'I reviewed the selected earlier content and want to restore it.',
    preview: 'Test an answer', question: 'Example patient question', workflow: 'Saved workflow AI node', test: 'Preview answer',
    previewHint: 'Uses the current approved KB and this saved AI node. No WhatsApp message is sent and no workflow actions run.',
    noNode: 'No saved AI Agent node exists in this clinic. Add one in Workflow Studio to preview.',
    outcome: 'Workflow outcome', handoff: 'Would hand off to staff', route: 'Would route to another step', no_match: 'No matching scenario', reply: 'Would reply',
    source: 'Sources used', diagnostics: 'Response diagnostics', clinicUsed: 'Clinic', nodeUsed: 'Workflow node', kbUsed: 'KB matches', retrievalUsed: 'Retrieval', helpMode: 'Docmee Help · no workflow node', emptyAnswer: 'The current workflow checks did not allow an answer.', newLesson: 'Teach another fact',
    error: 'The operation failed. Try again.', loading: 'Loading teaching options…', scope: 'Knowledge scope',
    limited: 'Showing the 200 most recently updated entries. Use Knowledge Base for older entries.',
    expires: 'Draft expires', openKb: 'Open Knowledge Base', historyEmpty: 'No published content to restore yet.',
    privacy: 'Use reusable clinic information, without patient names, contact details or private conversations.',
    errors: {
      duplicate_knowledge: 'This exact fact already exists in this scope. No new draft was created.',
      stale_candidate: 'The entry changed. Prepare a fresh proposal before confirming.',
      stale_sources: 'The KB changed since this draft. Prepare a fresh proposal and compare again.',
      expired_candidate: 'This draft expired. Prepare a new proposal.',
      remove_private_information: 'Remove personal contact details, patient names and links before saving.',
      mixed_source_scope: 'The selected entry belongs to a different doctor or language.',
      not_found: 'This clinic, doctor, entry or workflow is no longer available.',
    } as Record<string, string>,
  },
  es: {
    mode: 'Entrenar a J.zel', chat: 'Ayuda de Docmee', clinic: 'Clínica de destino', doctor: 'Doctor', allDoctors: 'Toda la clínica',
    recent: 'Lecciones recientes en este alcance', resume: 'Abrir lección',
    language: 'Idioma del conocimiento', allLanguages: 'Cualquier idioma', intro: 'Escribe un dato o una corrección de la clínica. El borrador no se publica hasta que lo revises y apruebes.',
    title: 'Título de la entrada', content: '¿Qué debe saber el agente?', target: 'Añadir o actualizar', newEntry: 'Añadir una entrada',
    create: 'Preparar propuesta', busy: 'Procesando…', draft: 'Borrador · pendiente de confirmación', approve: 'Aprobar esta entrada exacta',
    confirm: 'Revisé la clínica, el alcance y las entradas relacionadas. La información es correcta y está aprobada para responder a pacientes.',
    related: 'Posibles duplicados o conflictos', warning: 'La búsqueda de entradas relacionadas es limitada y no garantiza detectar todos los conflictos. Actualiza una entrada existente al sustituir un dato.',
    none: 'No se encontraron entradas relacionadas.', previous: 'Entrada actual', proposed: 'Entrada propuesta', edit: 'Revisar propuesta', status: 'Estado de publicación',
    approved: 'Aprobado · indexando. La búsqueda por palabras puede utilizar esta entrada.',
    ready: 'Listo para recuperar por el agente. Se siguen aplicando las verificaciones de respuesta.',
    indexing_failed: 'Aprobado · falló la indexación. Reinténtala para completar la preparación.',
    superseded: 'Esta versión ya no está disponible. Revisa la entrada actual en la base de conocimiento.',
    rejected: 'Rechazado', pending_review: 'Borrador', retry: 'Reintentar indexación', refresh: 'Actualizar estado',
    history: 'Historial de cambios', restore: 'Restaurar este contenido', restoreConfirm: 'Revisé el contenido anterior seleccionado y quiero restaurarlo.',
    preview: 'Probar una respuesta', question: 'Pregunta de ejemplo del paciente', workflow: 'Nodo de IA del flujo guardado', test: 'Vista previa',
    previewHint: 'Utiliza la base de conocimiento aprobada y este nodo guardado. No envía WhatsApp ni ejecuta acciones del flujo.',
    noNode: 'Esta clínica no tiene nodos de Agente IA guardados. Añade uno en Workflow Studio para probar.',
    outcome: 'Resultado del flujo', handoff: 'Derivaría al personal', route: 'Dirigiría a otro paso', no_match: 'Sin escenario coincidente', reply: 'Respondería',
    source: 'Fuentes utilizadas', diagnostics: 'Diagnóstico de la respuesta', clinicUsed: 'Clínica', nodeUsed: 'Nodo del flujo', kbUsed: 'Coincidencias KB', retrievalUsed: 'Recuperación', helpMode: 'Ayuda de Docmee · sin nodo del flujo', emptyAnswer: 'Las verificaciones del flujo actual no permitieron una respuesta.', newLesson: 'Enseñar otro dato',
    error: 'La operación falló. Inténtalo de nuevo.', loading: 'Cargando opciones…', scope: 'Alcance del conocimiento',
    limited: 'Se muestran las 200 entradas más recientes. Busca las anteriores en la base de conocimiento.',
    expires: 'El borrador vence', openKb: 'Abrir base de conocimiento', historyEmpty: 'Todavía no hay contenido publicado para restaurar.',
    privacy: 'Utiliza información general de la clínica, sin nombres de pacientes, datos de contacto ni conversaciones privadas.',
    errors: {
      duplicate_knowledge: 'Este dato exacto ya existe en este alcance. No se creó otro borrador.',
      stale_candidate: 'La entrada cambió. Prepara una nueva propuesta antes de confirmar.',
      stale_sources: 'La base de conocimiento cambió. Prepara otra propuesta y vuelve a comparar.',
      expired_candidate: 'El borrador venció. Prepara una nueva propuesta.',
      remove_private_information: 'Quita los datos personales, nombres de pacientes y enlaces antes de guardar.',
      mixed_source_scope: 'La entrada pertenece a otro doctor o idioma.',
      not_found: 'La clínica, doctor, entrada o flujo ya no está disponible.',
    } as Record<string, string>,
  },
}
export type TeachingCopy = typeof teachingCopy.en
